name: Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-rust-1.81.0-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rust-1.81.0-cargo-
            ${{ runner.os }}-cargo-

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@1.81.0
        with:
          components: clippy

      - name: Install cargo tools
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-audit,cargo-nextest,cargo-machete,cargo-tarpaulin

      - name: Audit
        if: ${{ github.event_name == 'push' }}
        run: cargo audit

      - name: Unused dependency check
        run: cargo machete

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Static analysis
        run: >
          cargo clippy --all-targets --all-features --
          -W clippy::pedantic
          -W clippy::nursery
          -W clippy::unwrap_used
          -W clippy::panic
          -W clippy::missing_panics_doc
          -W clippy::panic_in_result_fn
          -W clippy::cargo_common_metadata

      - name: Build tests (no run)
        run: cargo test --workspace --all-targets --all-features --no-run

      - name: Test
        run: cargo nextest run --workspace --all-targets --all-features --no-fail-fast --no-build

      - name: Coverage check
        env:
          CARGO_TARGET_DIR: target/tarpaulin
        run: cargo tarpaulin --fail-under 80